[package]
name = "fourviere-podcast"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
anyhow = "1.0"
lzma-rs = "0.3.0"
md5 = "0.7.0"
reqwest = { version = "0.11", features = ["blocking"] }
sevenz-rust = "0.5.3"
sha2 = "0.10.8"
tauri-build = { version = "1.5", features = [] }
tar = "0.4.40"
tempfile = "3.8.1"
zip-extract = "0.1.2"

[dependencies]
anyhow = "1.0.75"
function_name = "0.3.0"
log = "0.4.20"
mime_guess = "2.0.4"
reqwest = { version = "0.11", features = ["json"] }
rust-s3 = "0.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
suppaftp = { version = "5.2.2", features = ["async-native-tls"] }
tauri = { version = "1.5", features = [ "shell-sidecar", "dialog-all", "path-all", "fs-all", "shell-open", "process-command-api"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
thiserror = "1.0.50"
tokio = { version = "1", features = ["fs"] }
tokio-util = {version = "0.7.10", features = ["compat"] }

[dev-dependencies]
async-trait = "0.1.74"
hyper = { version = "0.14.27", features = ["http1", "http2", "server", "stream", "runtime"] }
libunftp = "0.19.0"
rss = "2.0.6"
s3s = "0.8.0"
s3s-fs = "0.8.0"
tokio = { version = "1", features = ["full"] }
unftp-sbe-fs = "0.2.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
