[package]
name = "fourviere-podcast"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
bytes = "1.0"
mime_guess = "2.0.4"
reqwest = { version = "0.11", features = ["json"] }
rust-s3 = "0.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
suppaftp = { version = "5.2.2", features = ["async-native-tls"]}
tauri = { version = "1.5", features = [ "dialog-all", "path-all", "fs-all", "shell-open"] }
tokio = { version = "1", features = ["fs"] }
tokio-util = {version = "0.7.10", features = ["compat"]}

[dev-dependencies]
async-trait = "0.1.74"
libunftp = "0.19.0"
rss = "2.0.6"
tokio = { version = "1", features = ["full"] }
unftp-sbe-fs = "0.2.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
